# Site Settings
title: My Resume
url: 'https://redbeard28.github.io/online-cv/'
baseurl: '/online-cv' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Jérémie CUADRADO
tagline: Freelance DevOps
pic: jcu_ronde_100x100.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Freelance on devops and big data. Full maker on IoT and 3D print FDM technology.'

#sidebar links
email: cv@redbeard-consulting.fr
phone: +33(0)6.34.48.45.38
website: blog.webjeda.com #do not add http://
linkedin: jeremiecuadrado
github: redbeard28
twitter: '@3dfabric28'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-104147870-2

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
